name: masiro
description: "A masiro client."
publish_to: 'none'

version: 0.1.0+14

environment:
  sdk: '>=3.4.4 <4.0.0'

isar_version: &isar_version 3.1.0+1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.6
  tray_manager: ^0.2.3
  window_manager: ^0.3.9
  go_router: ^14.2.1
  rxdart: ^0.28.0
  flutter_bloc: ^8.1.6
  flutter_smart_dialog: ^4.9.7+9
  shared_preferences: ^2.2.3
  dio: ^5.6.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  path: ^1.9.0
  path_provider: ^2.1.4
  html: ^0.15.4
  logger: ^2.4.0
  puppeteer: ^3.12.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  easy_refresh: ^3.4.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.5
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_isar_store: ^1.0.1
  isar: *isar_version
  isar_flutter_libs: *isar_version
  webview_flutter: ^4.9.0
  webview_cookie_manager:
    git:
      url: https://github.com/fryette/webview_cookie_manager
      ref: master
  flex_color_picker: ^3.6.0
  scrollable_positioned_list: ^0.3.8
  flutter_widget_from_html_core: ^0.15.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: any
  injectable_generator: ^2.4.2
  isar_generator: *isar_version
  flutter_launcher_icons: ^0.14.0
  flutter_oss_licenses: ^3.0.2


flutter:
  generate: true
  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/icon/icon.png
